color0 #000000
color1 #f06c6c
color2 #91c07e
color3 #e2a76f
color4 #d3d3ff
color5 #c9a0dc
color6 #bbdca0
color7 #eeeeee
color8 #3c3c3c
color9 #ff8080
color10 #bbdca0
color11 #f7a88c
color12 #d3d3ff
color13 #f6d0ff
color14 #c098c4
color15 #ffffff

cursor                #c9a0dc
cursor_text_color     #000000
background            #000000
foreground            #eeeeee
selection_foreground  #c9a0dc
selection_background  #3a2a4d
active_border_color   #c9a0dc
inactive_border_color #1a1a1a
url_color             #c9a0dc

active_tab_foreground   #000000
active_tab_background   #c9a0dc
inactive_tab_foreground #a5a5a5
inactive_tab_background #1a1a1a
cursor_trail_color      #a5a5a5
